#!/bin/sh -e

export VERSION=`cat uvicorn/__init__.py | grep __version__ | sed "s/__version__ = //" | sed "s/'//g"`
export PREFIX="venv/bin/"

find uvicorn -type f -name "*.py[co]" -delete
find uvicorn -type d -name __pycache__ -delete

${PREFIX}python setup.py bdist_wheel
${PREFIX}twine upload dist/* --repository=robbie_pypicloud

rm -r dist
